input:
  # Directory to scan
  directory: dist
output:
  # specify one of an output format: [csv, json, html, console] (default: console)
  format: html
other:
  # set true if you want to skip checking for newer version
  disable_version_check: false
  # update schedule for NVD database (default: daily)
  update: daily
  # set true if you want to autoextract archive files. (default: false)
  extract: true