name: CVE scanner
on:
#    You can customize this according to your need.
  - push
  - pull_request
jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build wheel
        run: |
          pip install wheel
          python setup.py bdist_wheel

      - uses: Niraj-Kamdar/cve-bin-tool-gh-action@master
        with:
          config: "cve_bin_tool_config.yml"
          output-filename: "cve_bin_tool_report.html"
